name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: node_modules
          key: ${{ runner.os }}-node-22-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-22-
      - run: npm ci
      - run: npm run lint
      - run: npm run test:run
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
